-- {
--   "lukas-reineke/indent-blankline.nvim",
--   main = "ibl",
--   opts = {},
--   config = function()
--     local highlight = {
--       "Yellow",
--       "Green",
--       "Pink",
--       "LightBlue",
--     }
--
--     local hooks = require("ibl.hooks")
--     -- create the highlight groups in the highlight setup hook, so they are reset
--     -- every time the colorscheme changes
--     hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
--       vim.api.nvim_set_hl(0, "Yellow", { fg = "#ffff40" })
--       vim.api.nvim_set_hl(0, "Green", { fg = "#7fff7f" })
--       vim.api.nvim_set_hl(0, "Pink", { fg = "#ff7fff" })
--       vim.api.nvim_set_hl(0, "LightBlue", { fg = "#4fecec" })
--     end)
--
--     require("ibl").setup({ indent = { highlight = highlight } })
--   end,
-- },

-- background color indentation guides
-- local highlight = {
--     "CursorColumn",
--     "Whitespace",
-- }
-- require("ibl").setup {
--     indent = { highlight = highlight, char = "" },
--     whitespace = {
--         highlight = highlight,
--         remove_blankline_trail = false,
--     },
--     scope = { enabled = false },
-- }
--

-- return {
--   {
--     "lukas-reineke/indent-blankline.nvim",
--     main = "ibl",
--     opts = {},
--     config = function()
--       local highlight = {
--         "RainbowRed",
--         "RainbowYellow",
--         "RainbowBlue",
--         "RainbowOrange",
--         "RainbowGreen",
--         "RainbowViolet",
--         "RainbowCyan",
--       }
--
--       local hooks = require("ibl.hooks")
--       -- create the highlight groups in the highlight setup hook, so they are reset
--       -- every time the colorscheme changes
--       hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
--         vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
--         vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#E5C07B" })
--         vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
--         vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#D19A66" })
--         vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#98C379" })
--         vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#C678DD" })
--         vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#56B6C2" })
--       end)
--
--       require("ibl").setup({ indent = { highlight = highlight } })
--     end,
--   },
-- }

return {}
